name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

   
    steps:
    - name: Print a message
      run: echo "Hello, this is a message from the CI pipeline!"
      